openapi: 3.0.1
info:
  version: 1.0.0
  title: "Trustbit Hackathon: Sustainable Logistics Simulation"
  description: API for the smart agents of the simulation
paths:
  /decide:
    post:
      description: 'Decide what to do next'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DecideRequest"
      responses:
        "200":
          description: A successful response with the next step for the simulation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/DecideResponse"

servers:
  - description: Locally running truck agent
    url: https://localhost:8080
components:
  schemas:
    DecideRequest:
      properties:
        truck:
          description: "Information about the truck"
          $ref: "#/components/schemas/TruckState"
        offers:
          description: "List of currently available cargo offers to deliver."
          type: array
          items:
            $ref: "#/components/schemas/CargoOffer"
        is_fleet:
          type: boolean
          example: false

    TruckState:
      properties:
        uid:
          description: "Truck ID, unique within the truck fleet of that team"
          type: integer
          minimum: 0
          example: 0
        loc:
          description: "The current location name where the truck is located"
          type: string
          example: "Rustport"
        balance:
          description: "The bank account balance of the truck driver / the truck fleet"
          type: number
          format: long
          example: 100.0
        driving_non_stop:
          description: "The amount of driving hours the truck driver is on the road"
          type: number
          format: long
          example: 3.25
        time:
          description: "Current simulation time. 13.25 means 13:15"
          type: number
          format: long
          minimum: 0.0
          maximum: 24.0
          example: 13.25

    CargoOffer:
      properties:
        uid:
          description: "Unique cargo ID"
          type: integer
          example: 0
        origin:
          description: "Location name where the cargo is currently located"
          type: string
          example: "Rustport"
        dest:
          description: "Destination location name for the cargo delivery"
          type: string
          example: "Berlin"
        name:
          description: "The name / description of the cargo"
          type: string
          example: "Cogs"
        price:
          description: "How much you earn for delivering the cargo"
          type: number
          format: long
          example: 100.1
        eta_to_cargo:
          description: "How long will it take the truck to get to the cargo origin location"
          type: number
          format: long
        km_to_cargo:
          description: "Distance between the truck and the cargo origin location"
          type: number
          format: long
        eta_to_deliver:
          description: "How long will it take the truck to deliver the cargo from the cargo origin location to its destination"
          type: number
          format: long
        km_to_deliver:
          description: "Distance between the cargo origin and the cargo destination location"
          type: number
          format: long

    DecideResponse:
      properties:
        command:
          type: string
          enum: [DELIVER, ROUTE, SLEEP]
          example: "DELIVER"
      discriminator:
        propertyName: command
        mapping:
          DELIVER: '#/components/schemas/DeliverResponse'
          ROUTE: '#/components/schemas/RouteResponse'
          SLEEP: '#/components/schemas/SleepResponse'
      anyOf:
        - $ref: '#/components/schemas/DeliverResponse'
        - $ref: '#/components/schemas/RouteResponse'
        - $ref: '#/components/schemas/SleepResponse'
  
    DeliverResponse:
      description: |
        Deliver a specific cargo. A lot of actions will happen automatically
        - Reserve a cargo for delivery
        - `ROUTE` to the cargo origin location
        - Load the cargo onto the truck
        - `ROUTE` to the cargo destination location
        - `SLEEP` Possibly the driver will need to sleep during the drive or at the destination, if he arrives outside of the destination's business hours
        - Unload the cargo at the destination
      allOf:
        - $ref: '#/components/schemas/DecideResponse'
        - type: object
          required:
            - argument
          properties:
            argument:
              description: "Unique cargo ID to deliver"
              type: integer
              example: "100"

    RouteResponse:
      description: "Drive the shortest route from the current truck location to a destination location"
      allOf:
        - $ref: '#/components/schemas/DecideResponse'
        - type: object
          required:
            - argument
          properties:
            argument:
              description: "The location name where the truck should drive to"
              type: integer
              example: "Rustport"

    SleepResponse:
      description: "Sleep for a certain amount of hours"
      allOf:
        - $ref: '#/components/schemas/DecideResponse'
        - type: object
          required:
            - argument
          properties:
            argument:
              description: "Number of hours to sleep"
              type: integer
              example: "1"
              
    WorldInfo:
      title: WorldInfo
      type: object
      properties:
        locations:
          type: array
          items:
            $ref: "#/components/schemas/Location"
        fuel_cost:
          type: number
          format: long
          example: 1.034
      required:
        - name
        - fuel_cost
        
    Location:
      title: Location
      type: object
      properties:
        name:
          type: string
        roads:
          type: object
          additionalProperties:
            type: number
            format: long
      required:
        - name
        - roads
